<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		<?php echo fetch_or_get($ufx["page_title"],$ufx["config"]["title"]); ?>
	</title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="title" content="<?php echo fetch_or_get($ufx["page_title"], $ufx["config"]["title"]); ?>"/>
    <meta name="description" content="<?php echo fetch_or_get($ufx["page_desc"], $ufx["config"]["description"]); ?>"/>
    <meta name="keywords" content="<?php echo fetch_or_get($ufx['page_kw'], $ufx["config"]["keywords"]);?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="icon" href="{%config site_favicon%}" type="image/png">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/bootstrap-v4.0.0.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/materialize.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/md-checkbox.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/general/style.master.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/general/style.mq.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/preloader.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/waitMe.min.css?v={%config version%}">

	<?php if (not_empty($ufx["app_statics"])): ?>
		<?php if (not_empty($ufx["app_statics"]["styles"])): ?>
			<?php foreach ($ufx["app_statics"]["styles"] as $file_path): ?>
				<link rel="stylesheet" href="<?php echo($file_path); ?>?v={%config version%}">
			<?php endforeach; ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php if (empty($ufx['is_logged'])): ?>
		<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/auth/style.master.css?v={%config version%}">
		<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/auth/style.mq.css?v={%config version%}">
	<?php endif; ?>
	
	<script src="{%config theme_url%}/statics/js/libs/jquery-3.5.1.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.form-v4.2.2.min.js?v={%config version%}"></script>
	<?php if ($ufx["server_mode"] == 'development'): ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.dev.min.js?v={%config version%}"></script>
	<?php else: ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.min.js?v={%config version%}"></script>
	<?php endif; ?>
	
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/validators.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/vuelidate.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/popper.1.12.9.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/bootstrap.v4.0.0.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/master.script.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/waitme/waitMe.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/clipboard.min.js?v={%config version%}"></script>

	<?php if (not_empty($ufx["app_statics"])): ?>
		<?php if (not_empty($ufx["app_statics"]["scripts"])): ?>
			<?php foreach ($ufx["app_statics"]["scripts"] as $file_path): ?>
				<script data-el="app-script" src="<?php echo($file_path); ?>?v={%config version%}"></script>
			<?php endforeach; ?>
		<?php endif; ?>
	<?php endif; ?>
</head>
<body>
	<div class="main-preloader-holder" id="main-preloader-holder">
		<div class="main-preloader">
			<div class="loading">
				<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
			</div>
		</div>
	</div>

	<main class="main-content-container <?php echo ufx_sidebar_status(); ?>" data-el="main-layout-content">
		<div class="main-content-container-inner">
			<?php echo ufx_template('general/header/content'); ?>

			<div data-el="main-layout-content" class="main-layout-content <?php echo ufx_sidebar_status(); ?>">
				<div class="left-part">
					<?php echo ufx_template('general/sidebar/content'); ?>
				</div>
				<div class="right-part">
					<?php echo($ufx["http_res"]); ?>
				</div>
			</div>
		</div>
	</main>

	<input id="csrf-token" type="hidden" class="hidden d-none" value="<?php echo fetch_or_get($ufx['csrf_token'],'none'); ?>">


	<div data-app="black-hole"></div>

	<?php echo ufx_template("general/scripts/app_master_script"); ?>

	<?php if (empty($ufx['is_logged'])): ?>
		<?php echo ufx_template("auth/includes/login"); ?>
		<?php echo ufx_template("auth/includes/signup"); ?>
		<?php echo ufx_template("auth/includes/resetpass"); ?>
		<?php echo ufx_template("auth/scripts/app_master_script"); ?>

		<?php if (not_empty($ufx['em_code'])): ?>
			<?php echo ufx_template("auth/includes/newpass"); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php if (not_empty($ufx['is_logged'])): ?>
		<?php echo ufx_template("general/modals/save_video"); ?>
		<?php echo ufx_template("general/modals/report_video"); ?>
	<?php endif; ?>
	
	<?php echo ufx_template("general/modals/language"); ?>

	<?php if (not_empty($ufx['config']['google_analytics'])): ?>
		<?php echo htmlspecialchars_decode($ufx['config']['google_analytics']); ?>
	<?php endif; ?>
</body>
</html>
